---


- name: Include OS-specific vars
  include_vars: "{{ ansible_os_family | lower }}.yml"

- include: RedHat/main.yml
  when: ansible_os_family == 'RedHat'

- include: hostname.yml
  tags:
    - hostname

- include: set_env.yml

- include: users/users-management.yml

- include: alternatives.yml

- include: swap.yml
  tags:
    - swap

- include: ssh.yml
  when: base_ssh

- include: utils.yml
