---

- hosts: all
  become: True
  pre_tasks:
    - package:
        name: hostname
        state: present
  roles:
    - role_under_test
  vars_files:
    - /etc/ansible/roles/role_under_test/local/base.yml
